CREATE TABLE IF NOT EXISTS trips (
   trip_id VARCHAR(50) NOT NULL,
   car_id INTEGER NOT NULL,
   driver_id INTEGER NOT NULL,
   car_number VARCHAR(50) NOT NULL,
   device_id VARCHAR(50) NOT NULL,
   trip_active INTEGER NOT NULL,
   start_message_id VARCHAR(50) NOT NULL,
   start_date TIMESTAMP NOT NULL,
   start_latitude DECIMAL NOT NULL,
   start_longitude DECIMAL NOT NULL,
   start_odo DECIMAL NOT NULL,
   stop_message_id VARCHAR(50) NOT NULL,
   stop_date TIMESTAMP NOT NULL,
   stop_latitude DECIMAL NOT NULL,
   stop_longitude DECIMAL NOT NULL,
   stop_odo DECIMAL NOT NULL,
   trip_duration INTEGER NOT NULL,
   trip_distance DECIMAL NOT NULL,
   trip_duration_night INTEGER NOT NULL,
   trip_distance_night INTEGER NOT NULL
);
